# Exemplo para deploy por Wrangler. Se usar painel do Cloudflare Pages, configure o binding DB no painel.
name = "amorsaudeexp4"
compatibility_date = "2026-06-29"
pages_build_output_dir = "."

# Preencha com os dados reais do seu D1 se for publicar por Wrangler:
# [[d1_databases]]
# binding = "DB"
# database_name = "NOME_DO_SEU_BANCO_D1"
# database_id = "ID_DO_SEU_BANCO_D1"
