name = "amorsaudeexp4"
main = "src/worker.js"
compatibility_date = "2026-07-28"
workers_dev = true
keep_vars = true

[observability]
enabled = true

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*", "/api", "/", "/pages/login", "/pages/home", "/modules/prontuario-medico/prontuario-medico"]
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "amorsaudeexp4-db"
database_id = "d3c0be5c-3170-42e0-9339-ecd1d61974fe"
